/*
    *
    * Wijmo Library 5.20172.359
    * http://wijmo.com/
    *
    * Copyright(c) GrapeCity, Inc.  All rights reserved.
    *
    * Licensed under the GrapeCity Commercial License.
    * sales@wijmo.com
    * wijmo.com/products/wijmo-5/license/
    *
    */
System.register(["wijmo/wijmo.grid.detail","@angular/core","@angular/common","wijmo/wijmo.angular2.directiveBase"],function(n,t){"use strict";var a=this&&this.__extends||function(){var n=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(n,t){n.__proto__=t}||function(n,t){for(var i in t)t.hasOwnProperty(i)&&(n[i]=t[i])};return function(t,i){function r(){this.constructor=t}n(t,i);t.prototype=i===null?Object.create(i):(r.prototype=i.prototype,new r)}}(),v=t&&t.id,h,c,i,r,l,e,f,u,s,o;return{setters:[function(n){h=n},function(n){c=n;i=n;r=n},function(n){l=n},function(n){e=n}],execute:function(){n("wjFlexGridDetailMeta",f={selector:'[wjFlexGridDetail]',inputs:['wjFlexGridDetail','maxHeight','detailVisibilityMode','rowHasDetail','isAnimated',],outputs:['initialized',],exportAs:'wjFlexGridDetail',providers:[]});u=function(n){function t(t,i,r,u,f,o){var s=n.call(this,r)||this,h;return s.isInitialized=!1,h=s._wjBehaviour=e.WjDirectiveBehavior.attach(s,t,i,r),s._viewContainerRef=u,s._templateRef=f,s._domRenderer=o,s._init(),s.created(),s}return a(t,n),t.prototype.created=function(){},t.prototype.ngOnInit=function(){this._wjBehaviour.ngOnInit()},t.prototype.ngAfterViewInit=function(){this._wjBehaviour.ngAfterViewInit()},t.prototype.ngOnDestroy=function(){this._wjBehaviour.ngOnDestroy()},t.prototype._init=function(){var n=this;this.createDetailCell=function(i,r){var o=e.WjDirectiveBehavior.instantiateTemplate(n.grid.hostElement,n._viewContainerRef,n._templateRef,n._domRenderer),u=o.viewRef,f=o.rootElement;return u.context.row=i,u.context.col=r,u.context.item=i.dataItem,f.parentElement.removeChild(f),f[t._viewRefProp]=u,f};this.disposeDetailCell=function(i){var u,r;i.detail&&(u=i.detail[t._viewRefProp])&&(i.detail[t._viewRefProp]=null,r=n._viewContainerRef.indexOf(u),r>-1&&n._viewContainerRef.remove(r))}},t}(h.FlexGridDetailProvider);u._viewRefProp='__wj_viewRef';u.meta={outputs:f.outputs};u.decorators=[{type:i.Directive,args:[{selector:f.selector,inputs:f.inputs,outputs:f.outputs,exportAs:f.exportAs,providers:[{provide:'WjComponent',useExisting:i.forwardRef(function(){return u})}].concat(f.providers)},]},];u.ctorParameters=function(){return[{type:i.ElementRef,decorators:[{type:r.Inject,args:[i.ElementRef,]},]},{type:i.Injector,decorators:[{type:r.Inject,args:[i.Injector,]},]},{type:undefined,decorators:[{type:r.Inject,args:['WjComponent',]},{type:r.SkipSelf},{type:i.Optional},]},{type:i.ViewContainerRef,decorators:[{type:r.Inject,args:[i.ViewContainerRef,]},]},{type:i.TemplateRef,decorators:[{type:r.Inject,args:[i.TemplateRef,]},]},{type:i.Renderer,decorators:[{type:r.Inject,args:[i.Renderer,]},]},]};n("WjFlexGridDetail",u);s=[u];o=function(){function n(){}return n}();o.decorators=[{type:c.NgModule,args:[{imports:[e.WjDirectiveBaseModule,l.CommonModule],declarations:s.slice(),exports:s.slice()},]},];o.ctorParameters=function(){return[]};n("WjGridDetailModule",o)}}})